{
	"_Type": "Action.Type.RestService.SendRequest",
	"ActionResult": {
		"_Name": "ResultRest"
	},
	"OnFailure": "/SkyCM_V2/Actions/Message/V2-Consulta/MsjSinInternet.action",
	"OnSuccess": "/SkyCM_V2/Rules/V2-Consulta/Rest_Pedido.js",
	"ShowActivityIndicator": true,
	"ActivityIndicatorText": "Cargando pedido espere un momento...",
	"Target": {
		"Service": "/SkyCM_V2/Services/Rest_Inventario.service",
		"Path": "/PedidoVendMovil",
		"OutputPath": "/MT_PedidoVendMovilResp/T_PedidoVendMovilResp/0/T_Cabecera",
		"RequestProperties": {
			"Method": "PUT",
			"Body": {
				"T_PedVendMovil": [
					{
						"Pedido": "#Page:EstadoPedido2/#Control:Fc_Num_Pedido/#Value",
						"Vendedor": "#Page:EstadoPedido2/#Control:Fc_Pernr2Pedidos/#Value",
						"Campocab1": "#Page:EstadoPedido2/#Control:FC_SOC/#Value"
					}
				]
			},
			"Headers": {
				"Content-Type": "application/json"
			}
		}
	}
}