{
	"_Type": "Action.Type.RestService.SendRequest",
	"ActionResult": {
		"_Name": "ResultRest"
	},
	"OnFailure": "/SkyCM_V2/Actions/Message/V2-Consulta/MsjSinInternet.action",
	"OnSuccess": "/SkyCM_V2/Rules/V2-Consulta/Rule_Rest_Inventario.js",
	"ShowActivityIndicator": true,
	"ActivityIndicatorText": "Buscando referencia espere un momento...",
	"Target": {
		"Service": "/SkyCM_V2/Services/Rest_Inventario.service",
		"Path": "/InvSkyVMovil",
		"OutputPath": "/MT_InvSkyVMovilAfsResp/T_InvSkyVMovilAfsResp/0/T_CabeceraInvSkyVMovil",
		"RequestProperties": {
			"Method": "PUT",
			"Body": {
				"T_InvSkyVMovilAfs": [
					{
						"Referencia": "#Page:Inventario2/#Control:FC_List_Referencia/#SelectedValue",
						"Vendedor": "#Page:Inventario2/#Control:FC_Pernr_Inv/#Value",
						"Campocab1": "#Page:Inventario2/#Control:FC_SOC/#Value"
					}
				]
			},
			"Headers": {
				"Content-Type": "application/json"
			}
		}
	}
}