{
	"_Type": "Action.Type.ODataService.DeleteEntity",
	"ActionResult": {
		"_Name": "delete"
	},
	"OnFailure": "/SkyCM_V2/Actions/Message/EliminarObjetivoEntityFailure.action",
	"OnSuccess": "/SkyCM_V2/Actions/CloseModalPage_Complete.action",
	"Target": {
		"EntitySet": "OBJEVISIT",
		"ReadLink": "{@odata.readLink}",
		"Service": "/SkyCM_V2/Services/SkyCM_V2.service"
	}
}