{
	"OnFailure": "/SkyCM_V2/Actions/Message/ErrorPermisosOtorgados.action",
	"OnSuccess": "/SkyCM_V2/Actions/ClosePage.action",
	"Properties": {
		"USRTY": "ADMN"
	},
	"Target": {
		"EntitySet": "VENDORINFO",
		"ReadLink": "{@odata.readLink}",
		"Service": "/SkyCM_V2/Services/SkyCM_V2.service"
	},
	"_Type": "Action.Type.ODataService.UpdateEntity"
}