{
	"_Type": "Action.Type.Message",
	"Message": "Desea realizar Check Out ?",
	"Title": "CheckOut Laboral",
	"OKCaption": "Si",
	"OnOK": "/SkyCM_V2/Actions/OData/CerrarJornadaActiva.action",
	"CancelCaption": "No"
}