{
	"_Type": "Action.Type.Navigation",
	"OnSuccess": "/SkyCM_V2/Actions/Service/SyncStartedMessage1.action",
	"PageToOpen": "/SkyCM_V2/Pages/Main.page",
	"ClearHistory": true,
	"ModalPage": false,
	"NavigationType": "Cross"
}