{
	"_Type": "Action.Type.CheckRequiredFields",
	"OnFailure": "/SkyCM_V2/Actions/Message/V2-Consulta/MsjCheckPedido.action",
	"OnSuccess": "/SkyCM_V2/Rules/Paises/ValidarSociedad.js",
	"RequiredFields": [
		"Fc_Num_Pedido"
	]
}