{
	"_Type": "Action.Type.RestService.SendRequest",
	"ActionResult": {
		"_Name": "ResultRest"
	},
	"OnFailure": "/SkyCM_V2/Actions/Message/V2-Consulta/MsjSinInternet.action",
	"OnSuccess": "/SkyCM_V2/Rules/Paises/Restpedidopais2.js",
	"Target": {
		"Service": "/SkyCM_V2/Services/Rest_paises.service",
		"Path": "/PedidoVendMovilPais",
		"OutputPath": "/MT_PedidoVendMovilResp/T_PedidoVendMovilResp/0/T_Cabecera",
		"RequestProperties": {
			"Method": "PUT",
			"Body": {
				"T_PedVendMovil": [
					{
						"Pedido": "#Page:EstadoPedido2/#Control:Fc_Num_Pedido/#Value",
						"Vendedor": "#Page:EstadoPedido2/#Control:FC_PERNR_PEDIDOS/#Value"
					}
				]
			}
		}
	}
}