{
	"_Type": "Action.Type.ProgressBanner",
	"OnSuccess": "/SkyCM_V2/Actions/OData/CerrarVisitaActiva_UpdateEntity.action",
	"Message": "Finalizando visita espere un momento...",
	"CompletionMessage": "Visita finalizada con exito.",
	"CompletionTimeout": 1,
	"Animated": true
}