{
	"_Type": "Action.Type.ProgressBanner",
	"OnSuccess": "/SkyCM_V2/Actions/OData/CerrarJornadaActivaOutTime.action",
	"Message": "Finalizando jornada laboral...",
	"CompletionMessage": "Jornada laboral finalizada con exito",
	"CompletionTimeout": 3,
	"Animated": true
}