{
	"_Type": "Action.Type.OfflineOData.Download",
	"OnSuccess": "/SkyCM_V2/Actions/ClosePage.action",
	"ShowActivityIndicator": true,
	"ActivityIndicatorText": "Refrescando sus visitas.......",
	"Service": "/SkyCM_V2/Services/SkyCM_V2.service",
	"DefiningRequests": [
		{
			"Name": "HISTV",
			"Query": "HISTV",
			"AutomaticallyRetrievesStreams": false
		}
	]
}