{
	"_Type": "Action.Type.OfflineOData.Initialize",
	"ActionResult": {
		"_Name": "init"
	},
	"OnSuccess": "/SkyCM_V2/Actions/Message/InicializacionExitosa.action",
	"ShowActivityIndicator": true,
	"ActivityIndicatorText": "Procesando..",
	"Service": "/SkyCM_V2/Services/SkyCM_V2.service",
	"DefiningRequests": [
		{
			"Name": "CAMPANA",
			"Query": "CAMPANA",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "CLIENTEINFO",
			"Query": "CLIENTEINFO",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "HISTV",
			"Query": "HISTV",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "IDENTIDADV",
			"Query": "IDENTIDADV",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "OBJEVISIT",
			"Query": "OBJEVISIT",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "PPTOVENDOR",
			"Query": "PPTOVENDOR",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "ROLES",
			"Query": "ROLES",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "VENDORCAMP",
			"Query": "VENDORCAMP",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "VENDORINFO",
			"Query": "VENDORINFO",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "WORKDAY",
			"Query": "WORKDAY",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "HISTV_ESPEJO",
			"Query": "HISTV_ESPEJO",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "WORKDAY_ESPEJO",
			"Query": "WORKDAY_ESPEJO",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "INVENTARIO_MX",
			"Query": "INVENTARIO_MX",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "IDENTIDADV_MX",
			"Query": "IDENTIDADV_MX",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "INVENTARIO",
			"Query": "INVENTARIO",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "CLIENTE_PROS",
			"Query": "CLIENTE_PROS",
			"AutomaticallyRetrievesStreams": false
		}
	],
	"ProgressText": {
		"Opening": "Comprobando requisitos de red...",
		"Initializing": "Enviando solicitud al servidor...",
		"InitialCommunication": "Iniciando conexión...",
		"StartingDownloadingFile": "Calculando tamaño de descarga...",
		"DownloadingFile": "Validando datos del servidor...",
		"StartingDownloadingData": "Descargando datos...",
		"DownloadingData": "Ultimando detalles...",
		"Opened": "Inicializacion exitosa!"
	}
}