{
	"_Type": "Action.Type.BannerMessage",
	"OnSuccess": "/SkyCM_V2/Actions/OData/Cli_Pros/CrearVisitaconjuntificacionProspecto.action",
	"Message": "Registrando Visita....",
	"Duration": 5,
	"Animated": true,
	"DismissBannerOnAction": true
}