{
	"OnFailure": "/SkyCM_V2/Actions/Message/NojustificacionNoCoordenadas.action",
	"OnSuccess": "/SkyCM_V2/Actions/OData/CrearVisitaconjuntificacion.action",
	"RequiredFields": [
		"FC_Justificacion"
	],
	"_Type": "Action.Type.CheckRequiredFields"
}