{
	"_Type": "Action.Type.ProgressBanner",
	"OnSuccess": "/SkyCM_V2/Actions/Rest/V2-consulta/Rest_Pedidos2.action",
	"Message": "Consultando espere un momento...",
	"CompletionMessage": "Consulta exitosa",
	"CompletionTimeout": 1,
	"Animated": true
}