{
	"_Type": "Action.Type.Navigation",
	"ShowActivityIndicator": false,
	"ActivityIndicatorText": "Cargando...",
	"PageToOpen": "/SkyCM_V2/Pages/Cli_Prosp/VisitaAClientePage.page",
	"NavigationType": "Inner"
}